name: PR watcher

on:
  pull_request

jobs:
  build:
    uses: ZaiusInc/ocp-github-actions/.github/workflows/build-node.yaml@OCP-784-refactor-release-gh
    secrets:
      nodeAuthToken: ${{ secrets.GITHUB_TOKEN }}
