name: PR watcher

on:
  pull_request

jobs:
  build:
    uses: ZaiusInc/node-sdk/.github/workflows/reusable-build.yaml@OCP-1008_fixing_reusable_builds
    secrets:
      nodeAuthToken: ${{ secrets.GITHUB_TOKEN }}
