name: PR watcher

on:
  pull_request

jobs:
  build:
    uses: ZaiusInc/node-sdk/.github/workflows/reusable-build.yaml@OCP-784-fix-reusable-workflows
    secrets:
      nodeAuthToken: ${{ secrets.GITHUB_TOKEN }}
